### ISSUE TITLE
Doc build failure with PyQt5 on gitpod

### ISSUE THREAD

**Issue by melonora** [napari/docs#176]
## 🐛 Bug
When attempting to build the docs in a gitpod environment with PyQt5 the build fails due to an error in drawing a visual. With Pyside2 I am able to complete the build.

## Environment
Output and environment can be found attached. I tried with both python 3.10 and 3.9, both resulting in the same error.

## Additional context

[sdtout.txt](https://github.com/napari/docs/files/11697110/sdtout.txt)
[environment.odt](https://github.com/napari/docs/files/11697127/environment.odt)

**Comment by melissawm** [comment]
I believe since you are using gitpod, you may have to use xvfb instead of "make docs" directly, like we do in CI. As far as I know, gitpod does not offer you a desktop where the GUI application can be initiated. Can you try looking at [our CI action](https://github.com/napari/docs/blob/b56f29569eadc6d321df8e39fa175b930529a364/.circleci/config.yml#L56) to see if this helps?

The command would be something like
```
xvfb-run --auto-servernum make docs-build GALLERY_PATH=../napari/examples/
```
where you can change the GALLERY_PATH to point to your set up on gitpod.

**Comment by Czaki** [comment]
The xvfb was used in this context. Without xvfb he will not reach visual problems.

**Comment by psobolewskiPhD** [comment]
@melonora Is this still an issue? A number of tweaks have been done...
Second, it looks like a issue with 3D, so might be pointing to something related to OpenGL and drivers.
