### ISSUE TITLE
Improve docs contributor's guide instructions with suggestions for environment setup for windows users

### ISSUE THREAD

**Issue by rwkozar** [napari/docs#19]
## 📚 Documentation
In contributing docs, the Building the docs section includes an option to use "make Docs" to generate documentation.  This does not work properly in Windows.

**Comment by DragaDoncila** [comment]
Thanks for raising this @rwkozar! I want to expand a bit and note that some of the other commands we use in our contributor's guide e.g. `rm -rf` don't work as expected on Windows. I think it's really important for us to provide these instructions, or show how to set up WSL for windows, or at the very least mention upfront that some of the instructions are unix specific.

**Comment by Czaki** [comment]
@rwkozar What did you mean that it is not working correctly? Do you meet this error? Or something different? 

```
Extension error (napari_sphinx_theme):
Handler <function add_google_calendar_secrets at 0x0000023702186940> for event 'build-finished' threw an exception (exception: 'charmap' codec can't decode byte 0x81 in position 206595: character maps to <undefined>)
make: *** [Makefile:9: docs] Error 2
```

**Comment by DragaDoncila** [comment]
@Czaki `make` is not pre-installed on windows so the error is just a generic "no valid command"

**Comment by Czaki** [comment]
python is also not pre-installed on Windows. Make could also not be installed on Ubuntu. 

But as you could see in my previous comment and in PR to `napar-sphix-theme` building docs do not work on Windows because of the bug in `napari-sphinx-theme`. So my question is if @rwkozar meet the same problem as me or reports a lack of documentation that there is a need to install make to do this step. 

googling how to install make is a smaller problem. I can not check at this moment but it looks like anaconda ships with `make`.

**Comment by DragaDoncila** [comment]
> So my question is if @rwkozar meet the same problem as me or reports a lack of documentation that there is a need to install make to do this step.

@Czaki ah I see, I wasn't aware of that existing issue. I should mention I answered the question with such authority as I am currently with @rwkozar at SciPy sprints, so I know the error he is referring to. I therefore asked him to raise this issue as many of the contributor's docs are not suitable for Windows users, even outside of the `make docs` command.

**Comment by Czaki** [comment]
Alternative for windows, if the user does not have `make`, is to execute `sphinx-build -b html . ./_build` from `docs` directory, but until https://github.com/napari/napari-sphinx-theme/pull/119 is merged and released, the building docs on windows will fail. 

other problems could be solved by using WSL or just bash for windows (for example, from git for windows https://git-scm.com/download/win)

**Comment by DragaDoncila** [comment]
@Czaki yep, I totally agree - perhaps we can edit this issue title to reflect the broader scope i.e. improving contributor's guide instructions for windows users. This would include suggestions to use WSL or bash for windows

**Comment by seankmartin** [comment]
Most of machines I have around these days happen to be Windows, so this is very relevant for me.

I've built documentation on windows so far using two methods:
1) I wrote a guide to set up WSL over on [zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/wsl2.20napari.20viewer.20issues/near/295740498). Once that is done, it's plain sailing! However, it is a bit of an effort if I'm honest, and I do think it would be a barrier to anyone on Windows who wants to contribute to docs.
2) With this in mind, I've recently been working on getting the makefile for this repository to be [cross platform](https://github.com/seankmartin/napari-docs/tree/cross_platform_make). For the most part, it involves replacing linux/mac specific commands with Windows equivalents. For me, this works currently using make from Windows command line (installed from [choco](https://chocolatey.org/)). I do understand that make is not preinstalled on Windows however, but I think we can describe how to install that.

For now, I'm mostly posting here in case in anyone looks up Windows issues in napari docs, as I still need to do more work here. Open to any thoughts on anything I've written though!

I think on the first part, it might be worth expanding on my old guide and incorporating a WSL guide into napari docs - any thoughts on where?

For the second part, I need to check if running the old makefile from bash on Windows works out of the box, or if the makefile changes I've made are needed for bash too. I'll probably try make a PR if I can confirm the new makefile works on Windows and hasn't regressed on linux. If the PR works out, then at least it means you don't have to use bash on windows (even if the old makefile works out of the box). If the PR does not work out, hopefully bash on windows works on the old makefile.

**Comment by seankmartin** [comment]
Just a quick follow up, the docs build works out of the box with bash for windows. So I'd highly recommend that.
Alternatively, all you need from WSL to build the docs is access to the "rm" command from Windows command prompt and access to make. You don't need to follow all the WSL steps to run napari from linux (where you need a Windows Xserver). So it is a lot simpler than the full napari/WSL setup.
Since these are both easy, I think improving the documentation around building the docs from Windows would be better than changing the actual makefile. I'll get to drafting up something on this topic.

I'll leave my [old branch](https://github.com/seankmartin/napari-docs/tree/cross_platform_make) hanging around in case anyone wants to build the docs on WIndows without WSL or bash for Windows.
