### ISSUE TITLE
Contributing Documentaiton guide is out of date

### ISSUE THREAD

**Issue by dstansby** [napari/docs#211]
## 🐛 Bug
The contributing documentation guide (https://napari.org/stable/developers/documentation/index.html) seems out of date. It does not mention this repository at all, and in the ["Before you start"](https://napari.org/stable/developers/documentation/index.html#before-you-start) section it references non existing folders in the main napari repo.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by psobolewskiPhD** [comment]
Gah! you're right! looks like we missed some PRs in the cherry pick to 0.4.18.
The `dev` docs are fine:
https://napari.org/dev/developers/documentation/index.html

This is another case where some content should just be fixed and not versioned, because contributing docs is a `dev` task...

I'm not sure what the best way to fix this is--maybe a patch to the GitHub.io repo to add an admonition to the contribution guide pointing to dev docs?
cc: @melissawm

**Comment by melissawm** [comment]
Yeah, I think that will be the best approach. Conceptually it is not really out of date - the stable version is 0.4.18,and that's how the repo looked at 0.4.18. It's just that the documentation for the state of the repo as it is now (on main) is always "latest".

Ive been looking at options to remove the home page and the developer docs from versioning but didn't find any that would be simple - I'll just go with what I can do now and maybe we can revisit later if there are better ways.

**Comment by melissawm** [comment]
Also, the version warning banner is here: https://github.com/napari/napari-sphinx-theme/pull/132

**Comment by psobolewskiPhD** [comment]
This will be fixed in 0.4.19 as the proper PR has been cherry picked over
https://github.com/napari/napari/pull/6384

**Comment by psobolewskiPhD** [comment]
I think with https://github.com/napari/napari.github.io/pull/406
and all the PRs mentioned above this can be closed?

**Comment by melissawm** [comment]
Closing, feel free to reopen in case this is still incomplete.
