### ISSUE TITLE
Add a footer/permanent site element with information on how to get help

### ISSUE THREAD

**Issue by melissawm** [napari/docs#218]
## 📚 New content request

This is (maybe) related to #62

The idea is to have a site element containing information on zulip, image.sc and how to get help with using napari (or developing with napari).

This would help folks more easily find the link to the communication channels, and hopefully make it easier for them to connect with the community.

### Outline

First draft: "If you need help with napari, make sure to join our zulip chat, or ask a question in the napari section of image.sc"

**Comment by seankmartin** [comment]
Related to this, if we get an overall help banner going, we might be able to move away from some snippets like in the [plugins section](https://napari.org/dev/plugins/start_using_plugins/index.html). Would be nice to have an overall looking for help section instead I think!

![image](https://github.com/napari/docs/assets/21295664/03e2a80e-fa45-4149-9170-a00b549aaf19)

**Comment by melissawm** [comment]
I had missed this, but it's related: #66

**Comment by melissawm** [comment]
Now that we have the announcement banner at the top of the pages, do we still want to keep this and #66 open?

**Comment by psobolewskiPhD** [comment]
I don't think @jni wanted the banner to be up full time, we just couldn't easily drop it -- that should be possible now right?
I think this is kinda adressed by: https://github.com/napari/napari-sphinx-theme/pull/168
Plus I think the updated community page helps:
https://github.com/napari/docs/pull/482

**Comment by jni** [comment]
Because I'm on holidays and that is a time to get wacky ideas, we could get a little chat bubble like the ubiquitous AI chatbots, except when you click on it it's just an overlay that says "Did you expect a large language model? Why not talk to a real human instead? Get help at the forum or in our Zulip chat room!" 😂 

Note: I am not serious, I hate overlays, they so easily overwhelm limited screen real-estate. But I agree that this can be closed by napari/napari-sphinx-theme#168
